[package]
name = "minigrep"
version = "0.1.0"
edition = "2021"
description = "A mini grep clone for learning Rust - Coding Dojo"
authors = ["Roach"]

[dependencies]

[dev-dependencies]

[[bin]]
name = "minigrep"
path = "src/main.rs"

[lib]
name = "minigrep"
path = "src/lib.rs"
